###
POST http://localhost:8080/api/restaurants/
Content-Type: application/json

{
  "name": "밥집",
  "address": "서울"
}
###
POST http://localhost:8080/api/restaurants/
Content-Type: application/json

{
  "name": "비룡",
  "address": "인천"
}
###
POST http://localhost:8080/api/restaurants/
Content-Type: application/json

{
  "name": "떡볶이",
  "address": "대구"
}